name: Go Lint

on:
  pull_request:
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "**/go.mod"
      - "**/go.sum"
      - ".github/workflows/lint.yml"
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "**/go.mod"
      - "**/go.sum"
      - ".github/workflows/lint.yml"
  merge_group:

permissions:
  contents: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run lint
        run: make lint
